"""One shared catalogue for shop, ownership and achievements."""
SLOTS = {
    "chapeu": "Chapéus",
    "roupa": "Roupas",
    "bandeira": "Bandeiras",
    "boia": "Boias",
    "boneco": "Bonecos",
    "acessorio": "Acessórios",
}

CATALOGO = [
    ("chapeu_palha",    "chapeu",   "Chapéu de palha",    0),
    ("chapeu_nenhum",   "chapeu",   "Sem chapéu",         0),
    ("chapeu_bone",     "chapeu",   "Boné azul",          150),
    ("chapeu_gorro",    "chapeu",   "Gorro de lã",        200),
    ("chapeu_quepe",    "chapeu",   "Quepe de capitão",   500),
    ("chapeu_pirata",   "chapeu",   "Chapéu de pirata",   800),
    ("chapeu_cartola",  "chapeu",   "Cartola",            1200),
    ("chapeu_coroa",    "chapeu",   "Coroa dourada",      5000),
    ("chapeu_pikachu",  "chapeu",   "Gorro de Rato Elétrico",   9999),
    ("chapeu_ninja",    "chapeu",   "Touca ninja",        1800),
    ("chapeu_samurai",  "chapeu",   "Elmo de samurai",    2600),
    ("chapeu_cowboy",   "chapeu",   "Chapéu de xerife",    950),
    ("chapeu_mago",     "chapeu",   "Chapéu de arquimago", 3200),
    ("chapeu_astronauta", "chapeu", "Capacete espacial",   4100),
    ("chapeu_folhas",   "chapeu",   "Coroa de folhas",     750),
    ("chapeu_marinheiro", "chapeu", "Boina de marinheiro", 650),
    ("chapeu_raposa",   "chapeu",   "Capuz de raposa",    2100),
    ("chapeu_corais",   "chapeu",   "Coroa de corais",    2900),

    ("roupa_vermelha",  "roupa",    "Camisa vermelha",    0),
    ("roupa_azul",      "roupa",    "Camisa azul",        100),
    ("roupa_verde",     "roupa",    "Colete verde",       250),
    ("roupa_listrada",  "roupa",    "Camisa listrada",    400),
    ("roupa_capa",      "roupa",    "Capa de chuva",      700),
    ("roupa_capitao",   "roupa",    "Casaco de capitão",  1500),
    ("roupa_gala",      "roupa",    "Traje de gala",      3000),
    ("roupa_ninja",     "roupa",    "Traje de ninja",     2200),
    ("roupa_astral",    "roupa",    "Manto estelar",      3500),
    ("roupa_mergulhador", "roupa",  "Traje de mergulho",   2800),
    ("roupa_fenix",     "roupa",    "Manto da fênix",      5200),
    ("roupa_cyber",     "roupa",    "Jaqueta cyberpunk",  4600),
    ("roupa_mago",      "roupa",    "Túnica de arquimago", 3900),
    ("roupa_marinheiro", "roupa",   "Uniforme de convés",  850),
    ("roupa_aurora",    "roupa",    "Manto da aurora",    4800),
    ("roupa_abisso",    "roupa",    "Armadura abissal",   6800),

    ("bandeira_nenhum",   "bandeira", "Sem bandeira",       0),
    ("bandeira_vermelha", "bandeira", "Bandeirinha vermelha", 100),
    ("bandeira_brasil",   "bandeira", "Bandeira do Brasil", 300),
    ("bandeira_arco",     "bandeira", "Bandeira arco-íris", 500),
    ("bandeira_pirata",   "bandeira", "Bandeira pirata",    1000),
    ("bandeira_dragao",   "bandeira", "Bandeira do dragão", 1300),
    ("bandeira_nebulosa", "bandeira", "Bandeira nebulosa",  1700),
    ("bandeira_sol",      "bandeira", "Bandeira do sol nascente", 1400),
    ("bandeira_kraken",   "bandeira", "Bandeira do kraken", 2100),
    ("bandeira_galaxia",  "bandeira", "Bandeira galáctica", 2400),
    ("bandeira_folhas",   "bandeira", "Bandeira da floresta", 950),
    ("bandeira_sakura", "bandeira", "Bandeira de sakura",  1150),
    ("bandeira_tempestade", "bandeira", "Bandeira da tempestade", 1850),
    ("bandeira_compasso", "bandeira", "Bandeira do explorador", 2750),

    ("boia_vermelha",   "boia",     "Boia vermelha",      0),
    ("boia_amarela",    "boia",     "Boia amarela",       100),
    ("boia_listrada",   "boia",     "Boia listrada",      250),
    ("boia_coracao",    "boia",     "Boia coração",       600),
    ("boia_estrela",    "boia",     "Boia estrela",       1500),
    ("boia_planeta",    "boia",     "Boia planeta",       2200),
    ("boia_bolha",      "boia",     "Boia de bolha",      1200),
    ("boia_donut",      "boia",     "Boia de rosquinha",   900),
    ("boia_abacaxi",    "boia",     "Boia de abacaxi",    1300),
    ("boia_kraken",     "boia",     "Boia do kraken",     2400),
    ("boia_foguete",    "boia",     "Boia foguete",       1800),
    ("boia_lotus",      "boia",     "Boia de lótus",       700),
    ("boia_limao",      "boia",     "Boia de limão",       1050),
    ("boia_perola",     "boia",     "Boia pérola lunar",   2800),

    ("boneco_nenhum",     "boneco", "Sem boneco",         0),
    ("boneco_pato",       "boneco", "Patinho de borracha", 300),
    ("boneco_caranguejo", "boneco", "Caranguejo",         700),
    ("boneco_gato",       "boneco", "Gatinho",            1500),
    ("boneco_pinguim",    "boneco", "Pinguim",            3000),
    ("boneco_agumon",     "boneco", "Dragão Digital",             9999),
    ("boneco_robot",      "boneco", "Robô explorador",    6000),
    ("boneco_slime",      "boneco", "Mascote gelatinoso", 4500),
    ("boneco_raposa",     "boneco", "Raposa mística",     3800),
    ("boneco_polvo",      "boneco", "Polvo de pelúcia",   2600),
    ("boneco_capivara",   "boneco", "Capivara aventureira", 3300),
    ("boneco_fantasma",   "boneco", "Fantasma camarada",  2200),
    ("boneco_tartaruga", "boneco", "Tartaruguinha",       1800),
    ("boneco_axolote",   "boneco", "Axolote sorridente",  2700),
    ("boneco_baleia",    "boneco", "Baleia viajante",     4100),

    ("acessorio_nenhum", "acessorio", "Sem acessório",          0),
    ("anel_verde_esmeralda", "acessorio", "Anel Verde-Esmeralda", 12000),
    ("martelo_pesado", "acessorio", "Martelo Pesado",            15000),
    ("teia_aracnidea", "acessorio", "Lançador de Teia",           10500),
    ("orbe_dragon", "acessorio", "Orbe do Dragão",                14000),
    ("broche_lunar", "acessorio", "Broche Lunar",                 11500),
    ("sabre_energia", "acessorio", "Sabre de Energia",             16000),
    ("asas_fenix", "acessorio", "Asas da Fênix",                    22000),
    ("aura_cyber", "acessorio", "Aura Cyberpunk",                   18500),
    ("estrelas_orbitais", "acessorio", "Constelação Orbital",       20000),
    ("chama_yokai", "acessorio", "Chamas de Yokai",                 23500),
    ("cajado_tempestade", "acessorio", "Cajado da Tempestade",       17000),
    ("escudo_bolhas", "acessorio", "Escudo de Bolhas",               19000),
    ("asas_boreais", "acessorio", "Asas Boreais",                     25000),
]
CATALOGO.append(('enciclopedia_viva','acessorio','Enciclopédia Viva',0))
CAT = {c[0]: c for c in CATALOGO}


def sold_items():
    return tuple(item for item in CATALOGO if item[3] > 0 and item[0] != "enciclopedia_viva")
